project:
  title: "myproject"
  type: default
  output-dir: docs-rendered
  render:
    - index.qmd
    # - docs-working/01_tidying_data.qmd
    # - docs-working/02_extracting_production_locations.qmd
    # - docs-working/03_assessing_species_potential.qmd
    # - docs-working/04_extracting_temperatures.qmd
    - docs-working/05_formulating_feeds.qmd
    - docs-working/06_how_many_runs_per_farm.qmd
    # - docs-working/07_run_atlantic_salmon_model.qmd
    - docs-working/08_data_analysis.qmd

editor: source

execute:
  eval: true

format:
  html:
    theme: cosmo
    css: "docs-working/extra.css"
    embed-resources: true
    code-fold: false
    code-overflow: wrap
    toc: true
    toc-expand: true
    toc-location: left
    number-sections: true
    lang: en-GB
    code-links:
      - text: Github
        icon: file-code
        href: https://github.com/stormeyseas/local_to_global_mariculture_modelling
    other-links:
      - text: Back to main
        href: https://drtreimer.com/local_to_global_mariculture_modelling
    fig-width: 8.5
    fig-height: 6.5
    fig-dpi: 600
    fig-format: png
    fig-align: center
    grid:
      sidebar-width: 250px
      body-width: 1200px
      margin-width: 250px
      gutter-width: 2em
  
bibliography: 
  - "docs-working/refs.bib"
  - "docs-working/manual-refs.bib"
  
notebook-links: global
