project:
  title: "myproject"
  type: default
  output-dir: docs-rendered
  render:
    - docs-working/index.qmd
    - docs-working/01_tidying_data.qmd
    - docs-working/02_extracting_production_locations.qmd
    - docs-working/03_assessing_species_potential.qmd
    - docs-working/04_extracting_temperatures.qmd
    - docs-working/05_formulating_feeds.qmd
    - 06_run_atlantic_salmon_model.qmd
    # - 07_species_layers.qmd
    # - 08_relative_N_inputs.qmd

editor: source

format:
  html:
    theme: cosmo
    css: "docs-working/extra.css"
    embed-resources: true
    code-fold: true
    code-overflow: wrap
    toc: true
    toc-expand: true
    toc-location: left
    number-sections: true
    lang: en-GB
    code-links:
      - text: Github
        icon: file-code
        href: https://github.com/stormeyseas/local_to_global_mariculture_modelling
    other-links:
      - text: Back to main
        href: https://drtreimer.com/local_to_global_mariculture_modelling
    fig-width: 8
    fig-height: 6
    fig-align: center
    grid:
      sidebar-width: 250px
      body-width: 1200px
      margin-width: 250px
      gutter-width: 2em
  
execute:
  eval: true
  freeze: auto
  cache: true

bibliography: 
  - "docs-working/refs.bib"
  - "docs-working/manual-refs.bib"

# acronyms:
#   insert_loa: false
#   keys:
#     - shortname: IMTA
#       longname: Integrated Multi-Trophic Aquaculture
#     - shortname: SHOC
#       longname: Sparse Hydrodynamic Ocean Code
#     - shortname: CONNIE3
#       longname: CONNectivity InterfacE, version 3
  
notebook-links: global
